version: 2

project_name: sbserver

before:
  hooks:
    - go mod tidy

builds:
  - id: sbserver
    main: ./cmd/sbserver
    binary: sbserver
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: sbserver
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^test:"
      - "^chore:"

dockers:
  - id: sbserver-amd64
    image_templates:
      - "ghcr.io/ericls/gosafe5:{{ .Version }}-amd64"
    goarch: amd64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
  - id: sbserver-arm64
    image_templates:
      - "ghcr.io/ericls/gosafe5:{{ .Version }}-arm64"
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/ericls/gosafe5:{{ .Version }}"
    image_templates:
      - "ghcr.io/ericls/gosafe5:{{ .Version }}-amd64"
      - "ghcr.io/ericls/gosafe5:{{ .Version }}-arm64"
  - name_template: "ghcr.io/ericls/gosafe5:latest"
    image_templates:
      - "ghcr.io/ericls/gosafe5:{{ .Version }}-amd64"
      - "ghcr.io/ericls/gosafe5:{{ .Version }}-arm64"

release:
  github:
    owner: ericls
    name: gosafe5

snapshot:
  version_template: "{{ .Tag }}-next"
